import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-corporate-card-rebate-fee-recovery",
  "engine": "recovery",
  "title": "Corporate Card Rebate & Fee Recovery",
  "shortTitle": "Corporate Card Rebate and Fee Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through corporate card rebate & fee recovery",
  "industry": "Corporate Card Economics",
  "uiPort": 4600,
  "apiPort": 5600,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Corporate Card Rebate & Fee Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidRebate",
    "expectedKey": "earnedRebate",
    "actualLabel": "Paid Rebate and Credits",
    "expectedLabel": "Contract-Earned Rebate",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Corporate Card Rebate & Fee Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("issuer-agreement-library","CCR01","Issuer agreement library","Execute issuer agreement library using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed issuer agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Issuer agreement library Reference","text","CCR01-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("account-card-hierarchy","CCR02","Account card hierarchy","Execute account card hierarchy using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed account card hierarchy decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Account card hierarchy Reference","text","CCR02-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("transaction-ingestion","CCR03","Transaction ingestion","Execute transaction ingestion using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Transaction ingestion Reference","text","CCR03-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("eligible-spend-calculation","CCR04","Eligible spend calculation","Execute eligible spend calculation using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed eligible spend calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Eligible spend calculation Reference","text","CCR04-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("rebate-tier-calculation","CCR05","Rebate tier calculation","Execute rebate tier calculation using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed rebate tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Rebate tier calculation Reference","text","CCR05-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("growth-bonus-validation","CCR06","Growth bonus validation","Execute growth bonus validation using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed growth bonus validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Growth bonus validation Reference","text","CCR06-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("large-ticket-adjustment","CCR07","Large-ticket adjustment","Execute large-ticket adjustment using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed large-ticket adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Large-ticket adjustment Reference","text","CCR07-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("virtual-card-analysis","CCR08","Virtual card analysis","Execute virtual card analysis using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed virtual card analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Virtual card analysis Reference","text","CCR08-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("ghost-card-analysis","CCR09","Ghost card analysis","Execute ghost card analysis using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed ghost card analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Ghost card analysis Reference","text","CCR09-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("foreign-exchange-fee-audit","CCR10","Foreign exchange fee audit","Execute foreign exchange fee audit using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed foreign exchange fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Foreign exchange fee audit Reference","text","CCR10-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("late-fee-validation","CCR11","Late fee validation","Execute late fee validation using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed late fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Late fee validation Reference","text","CCR11-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("intercompany-exclusion-control","CCR12","Intercompany exclusion control","Execute intercompany exclusion control using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed intercompany exclusion control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Intercompany exclusion control Reference","text","CCR12-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("statement-reconciliation","CCR13","Statement reconciliation","Execute statement reconciliation using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed statement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Statement reconciliation Reference","text","CCR13-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("issuer-claim-workflow","CCR14","Issuer claim workflow","Execute issuer claim workflow using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed issuer claim workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Issuer claim workflow Reference","text","CCR14-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]}),
feature("rebate-cash-reconciliation","CCR15","Rebate cash reconciliation","Execute rebate cash reconciliation using issuer agreements, card hierarchies, transactions, eligible spend, rebate tiers, growth bonuses, large-ticket adjustments, foreign exchange, fees, statements, and payments.","Produce a governed rebate cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Issuer / Card Program","text","Issuer / Card Program · Standard Case"],["caseReference","Rebate cash reconciliation Reference","text","CCR15-2026-001"],["paidRebate","Paid Rebate and Credits","currency",586500],["earnedRebate","Contract-Earned Rebate","currency",692070],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidRebate",subjects:["Issuer agreement library case","Account card hierarchy case","Transaction ingestion case","Eligible spend calculation case","Rebate tier calculation case"]})
]);
